name: Build jar

on:
  pull_request:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build jar
        run: |
          ./gradlew test
          ./gradlew build
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: build/libs/*.jar